Class.define('app.views.medications.mentalHealth.dto.MentalHealthTemplate', 'tm.jquery.Object', {
  statics: {
    /**
     * @param {object} jsonObject
     * @param {app.views.common.AppView} view
     * @return {app.views.medications.mentalHealth.dto.MentalHealthTemplate|null}
     */
    fromJson: function(jsonObject, view)
    {
      if (tm.jquery.Utils.isEmpty(jsonObject)) return null;
      var config = jQuery.extend(true, {}, jsonObject);
      config.route = config.route ?
          new app.views.medications.common.dto.MedicationRoute(config.route) :
          null;
      return new app.views.medications.mentalHealth.dto.MentalHealthTemplate(config).updateFormattedDisplay(view);
    }
  },
  id: null,
  name: null,
  code: null,
  route: null,
  formattedTherapyDisplay: null,

  Constructor: function(config)
  {
    this.callSuper(config);
  },

  /**
   * @return {number|null}
   */
  getId: function()
  {
    return this.id;
  },

  /**
   * @return {string|null}
   */
  getName: function()
  {
    return this.name;
  },

  /**
   * @return {string|null}
   */
  getCode: function()
  {
    return this.code;
  },

  /**
   * @return {app.views.medications.common.dto.MedicationRoute|null}
   */
  getRoute: function()
  {
    return this.route;
  },

  /**
   * Should be generated by the UI, unlike for other Therapy instances.
   * @return {string|null}
   */
  getFormattedTherapyDisplay: function()
  {
    return this.formattedTherapyDisplay;
  },

  /**
   * Generates the {@link #formattedTherapyDisplay} used by {@link app.views.medications.common.therapy.TherapyContainer}
   * to display the description. Normally this is server side generated HTML, but in case of mental health entities we
   * generate it on the client.
   * @param {app.views.common.AppView} view
   * @return {app.views.medications.mentalHealth.dto.MentalHealthTemplate} self
   */
  updateFormattedDisplay: function(view)
  {
    var routeName = this.getRoute() ? this.getRoute().getName() : view.getDictionary('all');

    var html = "";
    html += '<span class="TemplateName TextData">' + this.getName() + ' </span>';
    html += '<br />';
    html += '<span class="Route TextLabel">' + view.getDictionary("route.short").toUpperCase() + ' </span>';
    html += '<span class="Route TextData">' + routeName + ' </span><br />';

    this.formattedTherapyDisplay = html;
    return this;
  },

  /**
   * @param {boolean} [deep=true]
   * @return {app.views.medications.mentalHealth.dto.MentalHealthTemplate}
   */
  clone: function(deep)
  {
    return deep !== false ?
        jQuery.extend(true, new app.views.medications.mentalHealth.dto.MentalHealthTemplate(), this) :
        jQuery.extend(new app.views.medications.mentalHealth.dto.MentalHealthTemplate(), this);
  }
});
